### PR TITLE
Russiano

### PR DESCRIPTION
**Pull request by bogachenkove**
@jspenguin2017

### CODE REVIEW

**Comment by jspenguin2017** [comment]
The file you modified is a compiled binary, and will be overwritten each build. To make your change persistent, submit them here: https://crowdin.com/project/nano-adblocker

**Comment by bogachenkove** [comment]
I do not have an account there. and I do not plan to create it. Okay, let it not be translated.

**Comment by jspenguin2017** [comment]
You don't need another account -- just login with the GitHub account that you already have.

**Comment by bogachenkove** [comment]
I sent you the translation there @jspenguin2017 
Anyway, this is stupid. It is not comfortable. And I'm not sure I'd think of going there again.

**Comment by jspenguin2017** [comment]
This is the system that Nano and uBlock Origin use. It is pretty good once you get used to it. 

Note that you won't be able to change compiled locale files directly for upstream neither: 
`https://github.com/gorhill/uBlock/pull/5`
`https://github.com/gorhill/uBlock/issues/2921`
`https://github.com/gorhill/uBlock/issues/3475`
Just to list a few.

**Comment by bogachenkove** [comment]
> once you get used to it.

I hope it did not happen
***
I don’t know how often you check this service (or you get a notification here) ... in short, I made changes, check back.
***
Q: How to be with https://github.com/jspenguin2017/uBlockProtector ? There is only English. Can @jspenguin2017  do a language change function? I would translate to you.
***
_You have closed the tab "issues", so I ask here_
Q2: (not about translation) Your product uses 2 sheets of resources (scriptlets), suppose, just assume that I have another list (for) that I would like to (subscribe to) import. for personal purposes. This feature is not. How do you look at adding it?

The addition of this feature has already been asked here `https://github.com/uBlockOrigin/uBlock-issues/issues/226 `
but `gorhill`  did not answer, read (maybe he did not read) and did not answer. **Although not rejected!**

but I ask (specifically) you.
Do this for a long time?

**Comment by jspenguin2017** [comment]
> I don’t know how often you check this service

I check it every day or every few days. 

> How to be with https://github.com/jspenguin2017/uBlockProtector ?  There is only English.

Chances are I'll add internationalization during the manifest V3 migration. 

> Your product uses 2 sheets of resources

`gorhill` said he will add support for multiple `userResourcesLocation` soon: `https://github.com/uBlockOrigin/uAssets/issues/5184#issuecomment-475875189`

Note that Nano Adblocker will load the second resources manifest internally and does not take up the `userResourcesLocation` slot.

**Comment by jspenguin2017** [comment]
> but `gorhill` did not answer

I can't comment on this, as I'm not `gorhill`. If you believe he missed something, it's up to you to reach out to him.

**Pull request closed without merging**
